# Generated by Django 2.2.8 on 2019-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingproduct',
            old_name='schooltype',
            new_name='school_type',
        ),
        migrations.RemoveField(
            model_name='buildingproduct',
            name='company_logo',
        ),
        migrations.AlterField(
            model_name='buildingproduct',
            name='photo',
            field=models.ImageField(upload_to='product_photos'),
        ),
    ]
