# Generated by Django 2.2.8 on 2019-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0003_buildingproduct_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingproduct',
            name='company_logo',
            field=models.ImageField(default='product_photos/TaraElsen_wZKfXJQ.jpg', upload_to='company_logos'),
        ),
    ]
