# Generated by Django 2.2.8 on 2019-12-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0004_auto_20191214_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingproduct',
            name='company_logo',
            field=models.ImageField(default='company_logos/TaraElsen.jpg', upload_to='company_logos'),
        ),
    ]
