# Generated by Django 2.2.8 on 2019-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0006_buildingproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingproduct',
            name='company_name',
            field=models.CharField(default='Bouwfabriek', max_length=200),
        ),
    ]
