# Generated by Django 2.2.8 on 2019-12-14 12:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0008_auto_20191214_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingproduct',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='buildingproduct',
            name='company_logo_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='company_logos/TaraElsen.jpg', upload_to='company_logos'),
        ),
    ]
