# Generated by Django 2.2.8 on 2019-12-14 12:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0010_auto_20191214_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingproduct',
            name='photo',
        ),
        migrations.AddField(
            model_name='buildingproduct',
            name='photo_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='product_photos/TaraElsen.jpg', upload_to='product_photos'),
        ),
    ]
