# Generated by Django 2.2.8 on 2019-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0011_auto_20191214_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingproduct',
            name='school_type',
            field=models.CharField(choices=[('MBO', 'MBO'), ('VMBO', 'VMBO'), ('HBO', 'HBO'), ('Opleidingsbedrijf', 'OPLEIDINGSBEDRIJF')], max_length=20),
        ),
    ]
