# Generated by Django 2.2.8 on 2019-12-14 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0015_auto_20191214_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingproduct',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MATERIALEN', 'Materialen'), ('CURSUS', 'Cursus')], default='CURSUS', max_length=17),
        ),
    ]
