# Generated by Django 2.2.8 on 2019-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_product', '0016_auto_20191214_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingproduct',
            name='school_type',
            field=models.CharField(choices=[('Praktijkonderwijs', 'Praktijkonderwijs'), ('MBO', 'MBO'), ('VMBO', 'VMBO'), ('HBO', 'HBO'), ('Opleidingsbedrijf', 'Opleidingsbedrijf')], default='MBO', max_length=20),
        ),
    ]
